In [1]:
import numpy as np
import pandas as pd
import json
import os

In [2]:
# Ex1
path = '/Users/quoccuongnguyen/Documents/TDTU/YEAR-4/HK1-2021-2022/Massive-Data/Code/Chapter1-MiningData/Demo'

files = os.listdir(path)
txtArr = []

for i in files:
    file = open(os.path.join(path, i), 'r')
    file = file.read().split(' ')
    for c in file:
        txtArr.append(c)

series = pd.Series(txtArr)

with open('Output.txt', 'w+') as f:
    for i in range(len(series.value_counts())):
        f.write(f'{series.value_counts().index[i]}:\t\t{series.value_counts()[i]}\n')

In [3]:
# Ex2

dict1 = {'key1': 1, 'key2': 3, 'key3': 2}
dict2 = {'key1': 1, 'key2': 2}

for key in dict1:
    if (key in dict2 and dict1[key] == dict2[key]):
        print(key, ':\t', dict1[key], ' is present in both side')

key1 :	 1  is present in both side


In [4]:
# Ex3:
dict3 = {'students': [{'firstName': 'Nikki', 'lastName': 'Roysden'},
                      {'firstName': 'Mervin', 'lastName': 'Friedland'},
                      {'firstName': 'Aron ', 'lastName': 'Wilkins'}],
         'teachers': [{'firstName': 'Amberly', 'lastName': 'Calico'},
                      {'firstName': 'Regine', 'lastName': 'Agtarap'}]}

json.dump(dict3, open('Output.json', 'w'))

In [5]:
# Ex 4:
def numpyCalculate(mode, a, b):
    if (mode == 1):
        return a * b
    if (mode == 2):
        return np.outer(a, b)
    if (mode == 3):
        return np.cross(a, b)
    if (mode == 4):
        return np.linalg.det(a)
    if (mode == 5):
        return np.linalg.norm(a)
    if (mode == 6):
        return a@b

In [6]:
v1 = np.random.randint(0,100,(3,))
v2 = np.random.randint(0,100,(3,))

m1 = np.random.randint(0,100,(3,2))
m2 = np.random.randint(0,100,(3,2))
m3 = np.random.randint(0,100,(3,3))


v1,v2,m1,m2,m3

(array([86, 45, 63]),
 array([50, 46, 35]),
 array([[75,  6],
        [79, 94],
        [57, 83]]),
 array([[43, 38],
        [62, 63],
        [84, 94]]),
 array([[64, 50, 64],
        [64,  0, 52],
        [16, 87, 36]]))

In [7]:
print('The multiplication of two given matrixes : ',numpyCalculate(1,m1,m2))
print('The outer product of two given vectors : ',numpyCalculate(2,v1,v2))
print('The cross product of two given vectors :',numpyCalculate(3,v1,v2))
print('The determinant of a given square array : ',numpyCalculate(4,m3,m3))
print('The determinant of an array : ',numpyCalculate(5,v1,v1))
print('The inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension: '
      ,numpyCalculate(6,v1,v2))

The multiplication of two given matrixes :  [[3225  228]
 [4898 5922]
 [4788 7802]]
The outer product of two given vectors :  [[4300 3956 3010]
 [2250 2070 1575]
 [3150 2898 2205]]
The cross product of two given vectors : [-1323   140  1706]
The determinant of a given square array :  -6784.00000000002
The determinant of an array :  115.71516754514077
The inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension:  8575


In [13]:
# Ex5
class Stack:
    def __init__(self):
        self.items=[]
    def push (self,item):
        self.items.append(item)
    def pop (self):
        return self.items.pop()
    def size(self):
        return len(self.items)
    def isEmpty(self):
        return self.size == 0
    def top(self):
        return self.items[-1]

1
0
1
0


In [33]:
st = Stack()
a = int(input("Enter decimal number: "))
print('Input :',a)
while a!=0:
    b = a%2
    a = a//2
    st.push(b)

print('Output :',end=' ')
while st.size() != 0:
    print(st.pop(),end='')

Input : 100
Output : 1100100

In [42]:
#Ex 6

def calBigInteger(a,b,o):
    if o =='+':
        return (a+b)
    if o =='-':
        return (a-b)
    if o =='*':
        return (a*b)
    if o =='/':
        return (a/b)


a = int(input('Enter 1st big number:'))
b = int(input('Enter 2nd big number:'))
o = input('Enter operator:')



1000000010
