In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
data = pd.read_csv('my_quotes.csv')
data.head()

Tacgia                     Link            Namsinh  \
0  Albert Einstein  /author/Albert-Einstein     March 14, 1879   
1     J.K. Rowling      /author/J-K-Rowling      July 31, 1965   
2  Albert Einstein  /author/Albert-Einstein     March 14, 1879   
3      Jane Austen      /author/Jane-Austen  December 16, 1775   
4   Marilyn Monroe   /author/Marilyn-Monroe      June 01, 1926   

                                                Tags  \
0   ['change', 'deep-thoughts', 'thinking', 'world']   
1                           ['abilities', 'choices']   
2  ['inspirational', 'life', 'live', 'miracle', '...   
3         ['aliteracy', 'books', 'classic', 'humor']   
4                   ['be-yourself', 'inspirational']   

                                               Quote  
0  “The world as we have created it is a process ...  
1  “It is our choices, Harry, that show what we t...  
2  “There are only two ways to live your life. On...  
3  “The person, be it gentleman or lady, who has ...  
4  “Imperfection is beauty, madness is genius and...

In [3]:
sentences = []
for i in data['Quote']:
    sentences.append(i)

len(sentences)

100

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(stop_words='english')

vectorizer.fit(sentences)
vectorizer.get_feature_names()

['000',
 '10',
 'abilities',
 'absolutely',
 'absurdities',
 'accept',
 'act',
 'actually',
 'admiration',
 'admit',
 'adventure',
 'ahead',
 'airless',
 'alive',
 'analyze',
 'angel',
 'angry',
 'animal',
 'answers',
 'anytime',
 'appearance',
 'aren',
 'art',
 'asleep',
 'attempt',
 'author',
 'avoid',
 'awfully',
 'baby',
 'bad',
 'bag',
 'balance',
 'bat',
 'battle',
 'beautiful',
 'beauty',
 'begin',
 'beholder',
 'belief',
 'believe',
 'bella',
 'best',
 'better',
 'bicycle',
 'big',
 'black',
 'bleed',
 'blunders',
 'book',
 'books',
 'boring',
 'born',
 'bought',
 'boy',
 'brain',
 'brave',
 'bravery',
 'break',
 'broken',
 'car',
 'carefully',
 'case',
 'casket',
 'cause',
 'caution',
 'cautiously',
 'cedric',
 'celebrate',
 'cells',
 'change',
 'changed',
 'changing',
 'characters',
 'chest',
 'children',
 'chin',
 'chocolate',
 'choice',
 'choices',
 'christian',
 'christianity',
 'church',
 'classic',
 'climb',
 'close',
 'closed',
 'closes',
 'coffin',
 'come',
 'comforted

In [5]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [6]:
for i in range(data.shape[0]):
    temp = {}
    temp['Author'] = data.loc[i]['Tacgia']
    v = CountVectorizer(stop_words='english')

    v.fit([data.loc[i]['Quote']])
    for t in v.get_feature_names():
        if t in temp:
            temp[t] += 1
        else:
            temp[t] = 1

    df = df.append(temp, ignore_index=True)

In [7]:
df.fillna(0,inplace=True)
df.head()

Author  changed  changing  created  process  thinking  world  \
0  Albert Einstein      1.0       1.0      1.0      1.0       1.0    1.0   
1     J.K. Rowling      0.0       0.0      0.0      0.0       0.0    0.0   
2  Albert Einstein      0.0       0.0      0.0      0.0       0.0    0.0   
3      Jane Austen      0.0       0.0      0.0      0.0       0.0    0.0   
4   Marilyn Monroe      0.0       0.0      0.0      0.0       0.0    0.0   

   abilities  choices  far  ...  ups  wants  write  written  tell  worthy  \
0        0.0      0.0  0.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   
1        1.0      1.0  1.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   
2        0.0      0.0  0.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   
3        0.0      0.0  0.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   
4        0.0      0.0  0.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   

   edge  needs  sword  whetstone  
0   0.0    0.0    0.0        0.0  
1   0.0    0.0    0.0        0.0  
2   0.0    0.0    0.0        0.0  
3   0.0    0.0    0.0        0.0  
4   0.0    0.0    0.0        0.0  

[5 rows x 502 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
column_names = df.columns.values
for i in range(len(column_names)):
  if df.dtypes[i]=='object':
    df[column_names[i]] = encoder.fit_transform(df[column_names[i]])

In [9]:
df.head()

Author  changed  changing  created  process  thinking  world  abilities  \
0       0      1.0       1.0      1.0      1.0       1.0    1.0        0.0   
1      26      0.0       0.0      0.0      0.0       0.0    0.0        1.0   
2       0      0.0       0.0      0.0      0.0       0.0    0.0        0.0   
3      30      0.0       0.0      0.0      0.0       0.0    0.0        0.0   
4      37      0.0       0.0      0.0      0.0       0.0    0.0        0.0   

   choices  far  ...  ups  wants  write  written  tell  worthy  edge  needs  \
0      0.0  0.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   0.0    0.0   
1      1.0  1.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   0.0    0.0   
2      0.0  0.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   0.0    0.0   
3      0.0  0.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   0.0    0.0   
4      0.0  0.0  ...  0.0    0.0    0.0      0.0   0.0     0.0   0.0    0.0   

   sword  whetstone  
0    0.0        0.0  
1    0.0        0.0  
2    0.0        0.0  
3    0.0        0.0  
4    0.0        0.0  

[5 rows x 502 columns]

In [10]:
train = pd.concat([df.loc[df['Author']==0][0:4],df.loc[df['Author']!=0]])
test = df.loc[df['Author']==0][5:]
x_train = train.values[:,:-1]
x_test = test.values[:,:-1]

print('--- x_train ---')
print(x_train)
print(x_train.shape)
print('\n--- x_test ---')
print(x_test)
print(x_test.shape)

--- x_train ---
[[ 0.  1.  1. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [38.  0.  0. ...  0.  0.  0.]
 [11.  0.  0. ...  0.  0.  0.]
 [21.  0.  0. ...  1.  1.  1.]]
(94, 501)

--- x_test ---
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(5, 501)


In [11]:
y_train = train.values[:,-1]
y_test = test.values[:,-1]

print('--- y_train ---')
print(y_train)
print(y_train.shape)
print('\n--- y_test ---')
print(y_test)
print(y_test.shape)

--- y_train ---
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
(94,)

--- y_test ---
[0. 0. 0. 0. 0.]
(5,)


In [27]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50)
])

In [28]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [29]:
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
3/3 [==============================] - 0s 2ms/step - loss: 2.8143 - accuracy: 0.0851
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 2.6490 - accuracy: 0.2979
Epoch 3/100
3/3 [==============================] - 0s 3ms/step - loss: 2.4926 - accuracy: 0.5851
Epoch 4/100
3/3 [==============================] - 0s 2ms/step - loss: 2.3362 - accuracy: 0.7660
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 2.1917 - accuracy: 0.9043
Epoch 6/100
3/3 [==============================] - 0s 2ms/step - loss: 2.0490 - accuracy: 0.9255

In [30]:
test_loss, test_acc = model.evaluate(x_test,y_test, verbose=2)

print('\nTest accuracy:', test_acc)

1/1 - 0s - loss: 3.0831 - accuracy: 1.0000

Test accuracy: 1.0


In [17]:
vectorizer = CountVectorizer(stop_words='english')

vectorizer.fit(['The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.'])
vectorizer.get_feature_names()

['changed', 'changing', 'created', 'process', 'thinking', 'world']

In [18]:
vector = vectorizer.transform(['The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.'])
vector_spaces = vector.toarray()

vector_spaces

array([[1, 1, 1, 1, 2, 1]])

In [82]:
for i, v in zip(['The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.'], vector_spaces):
    print(i)
    print(v)

The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.
[1 1 1 1 2 1]


In [32]:
test  = df.loc[df['Author']==0]